spring.application.name=Litix

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:55121:5432/litixdb}
spring.datasource.username=${DB_USERNAME:sal}
spring.datasource.password=${DB_PASSWORD}

spring.ai.vertex.ai.gemini.location=${GCP_LOCATION:us-central1}
spring.ai.vertex.ai.gemini.project-id=${GCP_PROJECT_ID}
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.response-timeout=120s
spring.ai.vertex.ai.gemini.chat.options.connect-timeout=120s
spring.ai.vertex.ai.gemini.chat.options.temperature=0.4
spring.ai.vertex.ai.gemini.chat.options.top-k=5
spring.ai.vertex.ai.gemini.chat.options.top-p=0.95


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration